<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="WireMock.Net" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Weather.Web\Weather.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Weather.Infrastructure.UnitTests\Fixtures\**\*.json" LinkBase="Fixtures" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
