<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);EXTEXP0018</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WireMock.Net" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Weather.Infrastructure\Weather.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Fixtures\**\*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
